name: CI

on: push
jobs:
  Test:
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
    strategy:
      fail-fast: false
      matrix:
        os:             [ubuntu-latest, windows-latest, macos-latest]
        nim-channel:    [stable, devel]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    name: ${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.nim-channel }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup nim
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ matrix.nim-channel }}

    - name: Install Numpy
      shell: bash
      run: |
        python -m pip install numpy
        python -m pip install find_libpython

    - name: Test
      shell: bash
      run: |
        export NIMPY_PY_EXES=python
        python --version
        LIBPYTHON=$(python -c 'import find_libpython; print(find_libpython.find_libpython())')
        echo "libpython: $LIBPYTHON"

        python -c "import numpy; print('numpy: ', numpy.__version__)"
        nim --version

        if [ "${{ matrix.os }}" = "macos-latest" ]
        then
          export NIMPY_LIBPYTHONS=$LIBPYTHON
        fi

        nimble test
