name: CI

on: push
jobs:
  Test:
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
    strategy:
      fail-fast: false
      matrix:
        os:             [ubuntu-latest, windows-latest, macos-latest]
        nim-channel:    [stable, devel]
        python-version: ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10"]
        exclude:
          - os: windows-latest
            python-version: "2.7" # DLL not found, specific to CI?
          - os: windows-latest
            python-version: "3.10" # FIXME: eval doesn't work

    name: ${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.nim-channel }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup nim
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ matrix.nim-channel }}

    - name: Install Numpy
      shell: bash
      run: |
        python -m pip install numpy

    - name: Test
      shell: bash
      run: |
        export NIMPY_PY_EXES=python
        python --version
        python -c "import numpy; print('numpy: ', numpy.__version__)"
        nim --version
        nimble test
